grpc:
  server:
    port: 59091
kafka:
  group-id: collector-sensor-group
  producer:
    bootstrap-server: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.yandex.practicum.serializer.CollectorAvroSerializer
  topic:
    hubs: telemetry.hubs.v1
    sensors: telemetry.sensors.v1
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  application:
    name: plus-smart-home-tech